[package]
name = "skip-icloud-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dirs = "5.0"
color-eyre = "0.6"
inquire = "0.7.5"
colored = "2.0"
