name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release for macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: skip-icloud-sync-macos
        path: target/release/skip-icloud-sync
